name: Deploy 
on:
  push:
    branches: [ main ]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3  
          
        with:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
             
              cd bahja-isaac-nas-discord-chatbot
              git pull
              npm i
            
              pm2 stop index.js
              pm2 start index.js --name chatbot
