name: Execute Remote SSH Commands

on:
  push:
    branches: [main]

jobs:
  execute-commands:
    name: Execute Commands
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
              cd bahja-isaac-nas-discord-chatbot/bahja-isaac-nas-discord-chatbot
              git pull
              npm install
              pm2 stop chatbot
              # Start chatbot
              pm2 start index.js --name chatbot
            
              # Logging completion of script execution
              echo "Script execution completed successfully."
